# Generated by Django 3.1.1 on 2020-09-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.FloatField()),
                ('diastolic', models.FloatField()),
                ('pulse', models.DecimalField(decimal_places=0, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
