# Generated by Django 3.1.1 on 2020-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugar',
            name='drug',
            field=models.BooleanField(default=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sugar',
            name='exercise',
            field=models.BooleanField(default=False, max_length=10, null=True),
        ),
    ]
