# Generated by Django 3.1.1 on 2020-11-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20201109_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercare',
            name='updated_at',
        ),
    ]
