# Generated by Django 3.1.1 on 2020-09-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20200923_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('body_fat', models.FloatField()),
                ('bmi', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
    ]
