# Generated by Django 3.1.1 on 2020-11-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_remove_usercare_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary_diet',
            name='tag',
        ),
    ]
