# Generated by Django 3.1.1 on 2020-11-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0004_remove_diary_diet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_diet',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
