# Generated by Django 3.1.1 on 2020-10-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_auto_20201008_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_diet',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pressure',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sugar',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
