# Generated by Django 3.1.1 on 2020-11-26 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_diary_diet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercare',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
