# Generated by Django 3.1.1 on 2020-10-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0006_auto_20201008_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=100)),
                ('reply_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
