# Generated by Django 3.1.1 on 2020-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0007_usercare'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_diet',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pressure',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sugar',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usercare',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weight',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
