# Generated by Django 3.1.1 on 2020-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='invite_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
