# Generated by Django 3.1.1 on 2020-10-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0002_patient_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
