# Generated by Django 3.1.1 on 2020-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0003_auto_20201026_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabete',
            name='anti_hypertensives',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diabete',
            name='diabetes_type',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diabete',
            name='insulin',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='diabete',
            name='oad',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
