# Generated by Django 3.1.1 on 2020-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0005_auto_20201106_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabete',
            name='anti_hypertensives',
            field=models.CharField(default='4', max_length=20),
        ),
    ]
