# Generated by Django 3.1.1 on 2020-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0007_auto_20201106_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabete',
            name='anti_hypertensives',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='diabete',
            name='insulin',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='diabete',
            name='oad',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
