# Generated by Django 3.1.1 on 2020-11-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0008_auto_20201106_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medi',
            name='hospitalname',
            field=models.CharField(default='hospital', max_length=20),
        ),
        migrations.AlterField(
            model_name='medi',
            name='typee',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
