# Generated by Django 3.1.1 on 2020-11-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0009_auto_20201106_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabete',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
